protected/controllers/MailController.php
<?php

class MailController extends Controller
{
	// Uncomment the following methods and override them if needed

    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('admin', 'sendMail'),
                'roles'=>array('m_email')
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionAdmin()
    {
        $this->pageTitle = "Массовая рассылка";
        $this->render('admin');
    }

    public function actionSendMail()
    {
        header('Content-type: application/json');
        $response = array();
        $mSender = new MailSender();
        if(isset($_POST['use_template_switch']))
        {
            if($mSender->sendTemplateMail($_POST['template'])) {
                $response['success'] = true;
                $response['text'] = 'Сообщения отправлены';
            } else {
                $response['success'] = false;
                $response['errors'] = 'Возникла ошибка при отправке сообщений';
                $response['text'] = 'Сообщения не отправлены';
            }
        } else {
            if (isset($_POST['text'])){
                $text = trim($_POST['text']);
                $text = trim($text, "<br/>");
                $text = trim($text, "&nbsp;");
                if ($text){
                    if($mSender->sendWritedMail($_POST['text'])) {
                        $response['success'] = true;
                        $response['text'] = 'Сообщения отправлены';
                    } else {
                        $response['success'] = false;
                        $response['errors'] = 'Возникла ошибка при отправке сообщений';
                        $response['text'] = 'Сообщения не отправлены';
                    }
                } else {
                    $response['success'] = false;
                    $response['errors'] = 'Сообщение не может быть пустым';
                    $response['text'] = 'Сообщения не отправлены';
                }

            } else {
                $response['success'] = false;
                $response['errors'] = 'Недостаточно параметров';
                $response['text'] = 'Сообщения не отправлены';
            }
        }

        echo CJSON::encode($response);
        Yii::app()->end();
    }
}

protected/controllers/NewsController.php
<?php

class NewsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'getNewsComments'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('addcomment'),
				'roles'=>array('user'),
			),
            array('allow',
                'actions'=>array('create','update'),
                'roles'=>array('m_content')
            ),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'roles'=>array('admin'),
			),
            array('allow',
                'actions'=>array('editcomment','deletecomment'),
                'roles'=>array('m_comment')
            ),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
        $news = $this->loadModel($id);

        if ($news->status_id != News::PUBLIC_NEWS_STATUS_ID){
            if (!Yii::app()->user->checkAccess('m_content')){
                $this->redirect(array('user/login'));
            }
        }

        $this->pageTitle = $news->title;
        $this->description = $news->description;
        $this->keywords = $news->keywords;
		$this->render('view',array(
			'model' => $news,
		));
	}

    public function actionGetNewsComments($id){
        echo $this->getCommentsAsHTML($id);
    }

    protected function getCommentsAsHTML($newsId){
        $news = $this->loadModel($newsId);
        $comment = new NewsComment();
        $totalCommentsCount = NewsComment::model()->countByAttributes(array('news_id' => $news->id));
        $allComments = NewsComment::GetAllNewsComments($news->id);

        $msgHTML = $this->renderPartial('_comments', array(
            'model' => $news,
            'totalCommentsCount' => $totalCommentsCount,
            'allComments' => $allComments,
            'fakeComment' => $comment
        ), true);

        return $msgHTML;
    }

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
        $this->layout = '';
		$model=new News;
        $model->author = new User();
        $model->status = new NewsStatus();

        $this->pageTitle = "Новая новость";

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['News']))
		{
			$model->attributes=$_POST['News'];
            $model->deleteImageFlag = $_POST['deleteImageFlag'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->short_id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
        $this->layout = '';
		$model = $this->loadModel($id);

        $this->pageTitle = "Редактирование <" . $model->title.">";

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['News']))
		{
			$model->attributes=$_POST['News'];
            $model->deleteImageFlag = $_POST['deleteImageFlag'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->short_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
        $this->pageTitle = "Все новости";

        $dataProvider = News::getAllNews();
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

    public function actionAddComment(){
        header('Content-type: application/json');
        $response = array();

        $comment = new NewsComment();
        if(isset($_POST['NewsComment']))
        {
            $_POST['NewsComment']['news_id'] = $_POST['News']['id'];
            $_POST['NewsComment']['user_id'] = Yii::app()->user->getId();
            $comment->attributes = $_POST['NewsComment'];
            if($comment->save()) {
                $response['success'] = true;
                $response['text'] = 'Комментарий сохранен';
                $response['html'] = $this->getCommentsAsHTML($_POST['news_id']);
            } else {
                $response['success'] = false;
                $response['errors'] = $comment->getErrors();
                $response['text'] = 'Комментарий не сохранен';
            }
        }
        echo CJSON::encode($response);
        Yii::app()->end();
    }

    public function actionEditComment(){
        header('Content-type: application/json');
        $response = array();

        if(isset($_POST))
        {
            $comment = NewsComment::model()->findByPk($_POST['id']);
            $comment->text = $_POST['text'];
            if($comment->save()) {
                $response['success'] = true;
                $response['text'] = 'Комментарий сохранен';
                $response['html'] = $this->getCommentsAsHTML($_POST['news_id']);
            } else {
                $response['success'] = false;
                $response['errors'] = $comment->getErrors();
                $response['text'] = 'Комментарий не сохранен';
            }
        }
        echo CJSON::encode($response);
        Yii::app()->end();
    }

    public function actionDeleteComment(){
        header('Content-type: application/json');
        $response = array();

        if(isset($_POST))
        {
            $comment = NewsComment::model()->findByPk($_POST['id']);
            $countOfRelatedComments = NewsComment::model()->countByAttributes(array('parent_id' => $_POST['id']));
            if ($countOfRelatedComments == 0){
                try {
                    $comment->delete();
                    $response['success'] = true;
                    $response['text'] = 'Комментарий удален';
                    $response['html'] = $this->getCommentsAsHTML($_POST['news_id']);
                } catch (Exception $e) {
                    $response['success'] = false;
                    $response['error'] = "Возникла ошибка при удалении комментария.";
                    $response['text'] = 'Комментарий не удален';
                }
            } else {
                $response['success'] = false;
                $response['error'] = "Нельзя удалить комментарий, на который есть ответы.";
                $response['text'] = 'Комментарий не удален';
            }

        }
        echo CJSON::encode($response);
        Yii::app()->end();
    }

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
        $this->pageTitle = "Управление новостями";
		$model=new News('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['News']))
			$model->attributes=$_GET['News'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return News the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=News::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param News $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='news-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>

	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->

<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Операции',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
	<meta name="language" content="ru">

    <?php if ($this->description) { ?>
        <meta name="Description" content="Семейный блог Дорофеевых. <?=$this->description?>">
        <meta property="og:description" content="<?=$this->description?>"/>
    <?php } else { ?>
        <meta name="Description" content="Семейный блог Дорофеевых. Наши новости, истории, мысли и важные события.">
        <meta property="og:description" content="Семейный блог Дорофеевых. Наши новости, истории, мысли и важные события."/>
    <?php } ?>

    <?php if ($this->keywords) { ?>
        <meta name="Keywords" content="Дорофеевы, семейный блог, <?=$this->keywords?>">
    <?php } else { ?>
        <meta name="Keywords" content="Дорофеевы, Дорофеев Дмитрий, Дорофеева Евгения, Дима и Женя, семейный блог, Yii, истории, новости, фотографии">
    <?php } ?>

    <?php if ($this->image) { ?>
        <meta property="og:image" content="<?=Yii::app()->request->getBaseUrl(true). $this->image . "?rnd=".rand(0,1000)?>"/>
    <?php } ?>

    <meta property="og:title" content="<?=CHtml::encode($this->pageTitle)?>" />
    <meta property="og:site_name" content="Семейный блог" />

    <meta name=robots content="index, follow">

	<!-- blueprint CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
	<![endif]-->
    <?php echo Yii::app()->bootstrap->init();?>

    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/form.css'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/main.css'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/news.css'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/switch.css'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/pager.css'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/comments.css'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/questions.css'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/mailSender.css'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/vendor/sweetalert-master/dist/sweetalert.css'); ?>


    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/adaptive/news-transform.css', '(min-width: 1025px)'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/adaptive/small-widescreen.css', '(max-width: 1500px)'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/adaptive/medium-width.css', '(max-width: 1300px)'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/adaptive/laptop.css', '(max-width: 1024px)'); ?>
    <?php Yii::app()->clientScript->registerCssFile(Yii::app()->request->baseUrl.'/css/adaptive/mobile.css', '(max-width: 600px)'); ?>



    <?php Yii::app()->clientScript->registerCssFile('http://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic-ext&n5ketp', 'all'); ?>

    <script src="http://maps.api.2gis.ru/2.0/loader.js?pkg=full&lazy=true" data-id="dgLoader"></script>
    <script src="http://vk.com/js/api/openapi.js" type="text/javascript"></script>

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <link rel="shortcut icon" href="/images/favicon.ico">
</head>

<body>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-99030733-1', 'auto');
    ga('send', 'pageview');
</script>

<?php
    Yii::app()->clientScript->registerScriptFile("/js/jquery.plugin.min.js", CClientScript::POS_HEAD);
    Yii::app()->clientScript->registerScriptFile("/js/jquery.countdown.min.js", CClientScript::POS_HEAD);
    Yii::app()->clientScript->registerScriptFile("/js/onLoad.js", CClientScript::POS_HEAD);
    Yii::app()->clientScript->registerScriptFile('/vendor/sweetalert-master/dist/sweetalert.min.js');
?>

<div class="container" id="page">
    <div id="bg-image"></div>
    <?php
    $this->widget('bootstrap.widgets.TbNavbar', array(
        'brand'=>'Главная',
        'collapse'=>true,
        'brandUrl'=>'/',
        'htmlOptions'=>array('class' => 'main_menu', 'id' => 'main_menu'),
        'items' => array(
            array(
                'class' => 'bootstrap.widgets.TbMenu',
                'htmlOptions'=>array('class'=>'pull-left main_elements'),
                'items' => array(
                    //array('label'=>'Главная', 'url'=>array('/site/index')),
                    array('label'=>'Новости', 'url'=>array('/news/index')),
                    array('label'=>'Вопрос-ответ', 'url'=>array('/questions/index'), 'visible'=>Yii::app()->user->checkAccess('c_question')),
                    array('label'=>'О нас', 'url'=>array('/site/about')),
                )
            ),
            array(
                'class'=>'bootstrap.widgets.TbMenu',
                'htmlOptions'=>array('class'=>'pull-right additional_elements'),
                'items'=>array(

                    array(
                        'label'=>'Профиль',
                        'visible'=>!Yii::app()->user->isGuest,
                        'items'=>array(
                            array('label'=>'Мои данные', 'url'=>array('user/update','id'=>Yii::app()->user->id),),
                            array('label'=>'Мои вопросы', 'url'=>array('questions/userQuestions')),
                            array('label'=>'Отписаться от новостей', 'visible'=>Yii::app()->user->isSubscribed(), 'url'=>array('user/subscribe','id'=>Yii::app()->user->id, 'subscribe'=>0)),
                            array('label'=>'Подписаться на новости', 'visible'=>!Yii::app()->user->isSubscribed(), 'url'=>array('user/subscribe','id'=>Yii::app()->user->id, 'subscribe'=>1)),
                        )),
                    array(
                        'label'=>'Администрирование',
                        'items'=>array(
                            array('label'=>'Пользователи', 'visible'=>Yii::app()->user->checkAccess('m_users'), 'url'=>array('/user/index')),
                            array('label'=>'Новости', 'visible'=>Yii::app()->user->checkAccess('m_content'), 'url'=>array('/news/admin')),
                            array('label'=>'Массовая рассылка', 'visible'=>Yii::app()->user->checkAccess('m_email'), 'url'=>array('/mail/admin')),
                        )),
                    array('label'=>'Войти', 'visible'=>Yii::app()->user->isGuest, 'url'=>array('/user/login')),
                    array('label'=>'Регистрация', 'visible'=>Yii::app()->user->isGuest, 'url'=>array('/user/signin')),
                    array('label'=>'Выйти', 'visible'=>!Yii::app()->user->isGuest, 'url'=>array('user/logout')),
                ),
            ),
        )
    ));
    ?>

    <?php
    $controller = Yii::app()->getController();
    $isHome = $controller->getId() === 'site' && $controller->getAction()->getId() === 'index';
    if($isHome){
        $this->widget('CarouselWidget');
        $this->widget('CountDownWidget');
    } else {
        if (isset($this->image) and $this->image){
    ?>
            <div class="page-image-box">
                <?php
                 echo CHtml::image($this->image,"",array(
                    "id" => 'page-image',
                ));
                ?>
            </div>
    <?php
            $this->widget('CountDownWidget');
        }
    }
    ?>



    <div class="main-content-box">
        <div class="content-box <?=($this->fullsize)?(''):('limit-content-width')?>">
            <?php if(isset($this->breadcrumbs)):?>
                <?php $this->widget('zii.widgets.CBreadcrumbs', array(
                    'links'=>$this->breadcrumbs,
                    'homeLink'=>CHtml::link('Главная', array('site/index')),
                )); ?><!-- breadcrumbs -->
            <?php endif?>

            <?php echo $content; ?>
        </div>
    </div>

    <?php $this->renderPartial('/site/footer'); ?>


</div><!-- page -->

</body>
</html>