protected/models/News.php
<?php

/**
 * This is the model class for table "news".
 *
 * The followings are the available columns in table 'news':
 * @property integer $id
 * @property string $short_id
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property string $preview
 * @property string $text
 * @property integer $sort
 * @property integer $show_on_main
 * @property string $createdate
 * @property integer $author_id
 * @property integer $status_id
 * @property integer $informed
 * @property integer $image
 *
 * The followings are the available model relations:
 * @property User $author
 * @property NewsStatus $status
 * @property NewsComment[] $newsComments
 */
class News extends CActiveRecord
{
    const PUBLIC_NEWS_STATUS_ID = 2;

    private $isNewNews;
    private $uploadedFile;
    public $deleteImageFlag = false;

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'news';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('short_id, title', 'required'),
            array('sort, show_on_main, author_id, status_id, informed', 'numerical', 'integerOnly'=>true),
            array('short_id', 'length', 'max'=>128),
            array('image', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true),
            array('title, description, keywords', 'length', 'max'=>512),
            array('preview, text', 'safe'),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('id, short_id, title, preview, text, sort, show_on_main, createdate, author_id, status_id', 'safe', 'on'=>'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'author' => array(self::BELONGS_TO, 'User', 'author_id'),
            'status' => array(self::BELONGS_TO, 'NewsStatus', 'status_id'),
            'newsComments' => array(self::HAS_MANY, 'NewsComment', 'news_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'short_id' => 'Уникальный идентификатор',
            'title' => 'Заголовок',
            'preview' => 'Превью',
            'text' => 'Текст',
            'description' => 'Краткое описание',
            'keywords' => 'Ключевые слова',
            'sort' => 'Порядок сортировки',
            'show_on_main' => 'Закрепить на главной',
            'createdate' => 'Дата создания',
            'author_id' => 'Автор',
            'status_id' => 'Статус',
            'informed' => 'Уже информарованы',
            'image' => 'Главное изображение'
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria=new CDbCriteria;

        $criteria->compare('id',$this->id);
        $criteria->compare('short_id',$this->short_id,true);
        $criteria->compare('title',$this->title,true);
        $criteria->compare('preview',$this->preview,true);
        $criteria->compare('text',$this->text,true);
        $criteria->compare('sort',$this->sort);
        $criteria->compare('show_on_main',$this->show_on_main);
        $criteria->compare('createdate',$this->createdate,true);
        $criteria->compare('author_id',$this->author_id);
        $criteria->compare('status_id',$this->status_id);

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return News the static model class
     */

    public function beforeSave(){
        $this->isNewNews = $this->isNewRecord;
        if (!$this->author_id){
            $this->author_id = Yii::app()->user->id;
        }

        $this->uploadedFile = CUploadedFile::getInstance($this, 'image');

        if ($this->deleteImageFlag){
            $this->image = '';
        } else {
            if ($this->uploadedFile !== NULL){
                $fileName = $this->short_id."-".$this->uploadedFile;
                $this->image = $fileName;
            } else {
                unset($this->image);
            }
        }

        return true;
    }

    public function afterSave(){
        if ($this->uploadedFile){
            $this->uploadedFile->saveAs(Yii::app()->basePath.'/../images/news/'.$this->image);
        }

        $this->informIfNeeded();
        return true;
    }

    private function informIfNeeded(){
        if (!$this->informed){
            if ($this->status_id == self::PUBLIC_NEWS_STATUS_ID){
                $mSender = new MailSender();
                $mSender->sendInformMessage($this);
                return $this->setLikeInformed();
            }
        }
        return true;
    }

    private function setLikeInformed(){
        parent::afterSave();
        $this->informed = 1;
        $this->isNewRecord = false;
        return $this->saveAttributes(array('informed' => 1));
    }

    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public static function getNotPriorityNews(){
        $criteria = array(
            'limit'=>6,
            'condition'=>'show_on_main = 0',
            'order'=>'createdate DESC'
        );
        $criteria = self::addUserAccessCondition($criteria);
        return new CActiveDataProvider('News', array(
            'criteria'=>$criteria,
            'pagination'=>false,
        ));
    }

    protected static function addUserAccessCondition($criteria){
        if (!Yii::app()->user->checkAccess('m_content')) {
            if (isset($criteria['condition'])) {
                $criteria['condition'] .= ' AND status_id >= '.self::PUBLIC_NEWS_STATUS_ID;
            } else {
                $criteria['condition'] = 'status_id >= '.self::PUBLIC_NEWS_STATUS_ID;
            }
        }
        return $criteria;
    }

    public static function getNewsToMainPage(){
        $criteria = array(
            'condition'=>'show_on_main=1',
            'order'=>'sort, createdate DESC'
        );
        $criteria = self::addUserAccessCondition($criteria);
        return new CActiveDataProvider('News', array(
            'criteria'=>$criteria,
        ));
    }

    public static function getAllNews(){
        $criteria = array(
            'order'=>'createdate DESC',
        );
        $criteria = self::addUserAccessCondition($criteria);
        return new CActiveDataProvider('News', array(
            'criteria'=>$criteria,
            'pagination'=>array(
                'pageSize'=>6,
            ),
        ));
    }
}

protected/controllers/NewsController.php
<?php

class NewsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'getNewsComments'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('addcomment'),
				'roles'=>array('user'),
			),
            array('allow',
                'actions'=>array('create','update'),
                'roles'=>array('m_content')
            ),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'roles'=>array('admin'),
			),
            array('allow',
                'actions'=>array('editcomment','deletecomment'),
                'roles'=>array('m_comment')
            ),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
        $news = $this->loadModel($id);

        if ($news->status_id != News::PUBLIC_NEWS_STATUS_ID){
            if (!Yii::app()->user->checkAccess('m_content')){
                $this->redirect(array('user/login'));
            }
        }

        $this->pageTitle = $news->title;
        $this->description = $news->description;
        $this->keywords = $news->keywords;
		$this->render('view',array(
			'model' => $news,
		));
	}

    public function actionGetNewsComments($id){
        echo $this->getCommentsAsHTML($id);
    }

    protected function getCommentsAsHTML($newsId){
        $news = $this->loadModel($newsId);
        $comment = new NewsComment();
        $totalCommentsCount = NewsComment::model()->countByAttributes(array('news_id' => $news->id));
        $allComments = NewsComment::GetAllNewsComments($news->id);

        $msgHTML = $this->renderPartial('_comments', array(
            'model' => $news,
            'totalCommentsCount' => $totalCommentsCount,
            'allComments' => $allComments,
            'fakeComment' => $comment
        ), true);

        return $msgHTML;
    }

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
        $this->layout = '';
		$model=new News;
        $model->author = new User();
        $model->status = new NewsStatus();

        $this->pageTitle = "Новая новость";

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['News']))
		{
			$model->attributes=$_POST['News'];
            $model->deleteImageFlag = $_POST['deleteImageFlag'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->short_id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
        $this->layout = '';
		$model = $this->loadModel($id);

        $this->pageTitle = "Редактирование <" . $model->title.">";

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['News']))
		{
			$model->attributes=$_POST['News'];
            $model->deleteImageFlag = $_POST['deleteImageFlag'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->short_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
        $this->pageTitle = "Все новости";

        $dataProvider = News::getAllNews();
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

    public function actionAddComment(){
        header('Content-type: application/json');
        $response = array();

        $comment = new NewsComment();
        if(isset($_POST['NewsComment']))
        {
            $_POST['NewsComment']['news_id'] = $_POST['News']['id'];
            $_POST['NewsComment']['user_id'] = Yii::app()->user->getId();
            $comment->attributes = $_POST['NewsComment'];
            if($comment->save()) {
                $response['success'] = true;
                $response['text'] = 'Комментарий сохранен';
                $response['html'] = $this->getCommentsAsHTML($_POST['news_id']);
            } else {
                $response['success'] = false;
                $response['errors'] = $comment->getErrors();
                $response['text'] = 'Комментарий не сохранен';
            }
        }
        echo CJSON::encode($response);
        Yii::app()->end();
    }

    public function actionEditComment(){
        header('Content-type: application/json');
        $response = array();

        if(isset($_POST))
        {
            $comment = NewsComment::model()->findByPk($_POST['id']);
            $comment->text = $_POST['text'];
            if($comment->save()) {
                $response['success'] = true;
                $response['text'] = 'Комментарий сохранен';
                $response['html'] = $this->getCommentsAsHTML($_POST['news_id']);
            } else {
                $response['success'] = false;
                $response['errors'] = $comment->getErrors();
                $response['text'] = 'Комментарий не сохранен';
            }
        }
        echo CJSON::encode($response);
        Yii::app()->end();
    }

    public function actionDeleteComment(){
        header('Content-type: application/json');
        $response = array();

        if(isset($_POST))
        {
            $comment = NewsComment::model()->findByPk($_POST['id']);
            $countOfRelatedComments = NewsComment::model()->countByAttributes(array('parent_id' => $_POST['id']));
            if ($countOfRelatedComments == 0){
                try {
                    $comment->delete();
                    $response['success'] = true;
                    $response['text'] = 'Комментарий удален';
                    $response['html'] = $this->getCommentsAsHTML($_POST['news_id']);
                } catch (Exception $e) {
                    $response['success'] = false;
                    $response['error'] = "Возникла ошибка при удалении комментария.";
                    $response['text'] = 'Комментарий не удален';
                }
            } else {
                $response['success'] = false;
                $response['error'] = "Нельзя удалить комментарий, на который есть ответы.";
                $response['text'] = 'Комментарий не удален';
            }

        }
        echo CJSON::encode($response);
        Yii::app()->end();
    }

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
        $this->pageTitle = "Управление новостями";
		$model=new News('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['News']))
			$model->attributes=$_GET['News'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return News the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=News::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param News $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='news-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/news/_commentEdit.php
<?php $this->beginWidget('bootstrap.widgets.TbModal', array('id'=>'edit-comment-modal')); ?>
    <div class="modal-header">

        <h3>Редактирование комментария</h3>
    </div>
    <div class="modal-body">
        <form id="edit-comment-form">
            <div id="comment-form-box" class="comment-form">
                <div class="comment_user"><b>Пользователь</b></div>
                <div class="comment_date">00-00-0000 00:00:00</div>
                <div class="comment_id">5</div>
                <textarea id="comment_text" name="text" class='comment-text'></textarea>
                <div class="parent-info-div"></div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label'=>'Сохранить',
            'type'=>'success',
            'htmlOptions'=>array('OnClick'=>'sendEditCommentRequest()'),
        )); ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label'=>'Отмена',
            'type'=>'danger',
            'htmlOptions'=>array('data-dismiss'=>'modal'),
        )); ?>
    </div>
<?php $this->endWidget(); ?>

protected/views/news/_comments.php
<h3>Комментарии <div class="comment-count">(<?=$totalCommentsCount?>)</div></h3>
<?php
    if (Yii::app()->user->checkAccess('c_comment')) {

        function createComment($comment){
            echo '<div class="comment-box">';
            echo '<div class="comment-info" id="comment-id-'.$comment['id'].'" onclick="saveAsParent(this,'.$comment['id'].')">';
            echo '<div class="comment_user"><b>'.$comment['user'].'</b></div>';
            echo '<div class="comment_date">'.$comment['date'].'</div>';
            echo '<div class="comment_text">';
            echo '<p>'.nl2br($comment['text']).'</p>';
            echo '</div>';
            if (Yii::app()->user->checkAccess('m_comment')){
                echo '<div class="comment-manager-box">';
                echo '<a class="comment-manager-link" onClick="editComment('.$comment['id'].', event)">Редактировать</a>';
                echo '<a class="comment-manager-link" onClick="deleteComment('.$comment['id'].', event)">Удалить</a>';
                echo '</div>';
            }
            echo '</div>';
            if ($comment['children']){
                foreach ($comment['children'] as $child){
                    createComment($child);
                }
            }
            echo '</div>';
        }

        foreach ($allComments as $comment){
            createComment($comment);
        }


        ?>

        <div id="comment-form-box" class="comment-form">
            <div class="comment_user"><b><?=Yii::app()->user->fullName?></b></div>
            <div class="comment_date"><?php
                echo strftime('%d %b %Y', time());
                ?>
            </div>
            <?php $form = $this->beginWidget('CActiveForm', array(
                'id'=>'comment-form',
                'enableClientValidation' => false,
                'htmlOptions'=>array(
                    'onsubmit'=>"return false;"
                )
            ));

            echo $form->textField($model,"id",array('class'=>"comment-news-id"));
            echo $form->textField($fakeComment,"parent_id",array('class'=>"comment-parent-id"));
            echo $form->textArea($fakeComment,'text',array('class'=>'comment-text'));
            ?>

            <?php
            echo CHtml::submitButton('Отправить',
                array(
                    'class' => 'site_button',
                    'id' => 'addcomment',
                    'onClick' => 'sendComment()'
                )
            );?>
            <div class="parent-info-div" id="parent-info"></div>
            <?php
            $this->endWidget();
            ?>
        </div>

        <?php $this->renderPartial('/news/_commentEdit'); ?>

<?php } else {
    echo "Чтобы увидеть комментарии пользователей, необходимо авторизоваться.";
} ?>

protected/views/news/_newsPreview.php
<?php
/* @var $this NewsController */
/* @var $data News */
?>

<div id="<?=$data->short_id?>" class="single_news preview">
    <div id="news-data">
        <news class="front">
            <div class="front_news_title_box">
                <div class="front_news_title">
                    <h2><?php echo CHtml::link(CHtml::encode($data->title), array('/news/view', 'id'=>$data->short_id)); ?></h2>
                </div>
            </div>
            <div class="news-main-image">
            <?php if($data->image){ ?>
                <?php echo CHtml::image('/images/news/'.$data->image,"",array(
                    "id" => 'newsMainImage',
                )); ?>
            <?php } else { ?>
                    <img id="newsMainImage" src="/images/no-news-image.png"/>
            <?php } ?>
            </div>
        </news>
        <news class="side"></news>
        <news class="back">
            <?php if (!isset($update)){?>
                <div class="news_title_box">
                    <div class="news_title">
                        <h2><?php echo CHtml::link(CHtml::encode($data->title), array('/news/view', 'id'=>$data->short_id)); ?></h2>
                    </div>
                    <?php if (Yii::app()->user->checkAccess('m_content')) {?>
                        <div class="news_status">
                            <?php echo CHtml::link(CHtml::encode($data->status->name), array('/news/update', 'id'=>$data->short_id)); ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } else { ?>
                <div class="news_title_box">
                    <div class="news_title">
                        <h2><?php echo CHtml::link(CHtml::encode($data->title), array('/news/view', 'id'=>$data->short_id)); ?></h2>
                    </div>
                </div>
            <?php } ?>

            <div class="news_preview">
                <?= ($data->preview)?($data->preview):($data->text)?>
            </div>

            <?php if (!isset($update)){?>
                <div class="news_footer_box">
                    <div class="news_read_more">
                        <?= CHtml::link(CHtml::encode('Подробнее'), array('/news/view', 'id'=>$data->short_id), array(
                            'class' => 'btn btn-info'
                        )); ?>
                    </div>

                    <?php if (Yii::app()->user->checkAccess('m_content')) { ?>
                        <div class="news_date">
                            <?=CHtml::encode($data->createdate)?>
                        </div>

                        <div class="news_comment_count">
                            (<?=NewsComment::model()->countByAttributes(array('news_id'=>$data->id)) ?>)
                        </div>

                        <div class="news_author">
                            <?php echo CHtml::encode($data->author->user_profile->FullName); ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
        </news>

    </div>
</div>

protected/views/news/_showImage.php
<?php $this->beginWidget('bootstrap.widgets.TbModal', array('id'=>'full-image-modal')); ?>
    <img id="fullsize-image" class="zoom-out" src=""/>
<?php $this->endWidget(); ?>

protected/views/news/admin.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->breadcrumbs=array(
	'Все новости'=>array('index'),
	'Управление новостями',
);

?>

<h1>Управление новостями</h1>
<?php echo CHtml::link('Создать новость',array('news/create'),array('class'=>'btn btn-sm')); ?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'news-grid',
	'dataProvider'=>$model->search(),
	'columns'=>array(
        array(
            'name' => 'id',
            'value' => '$data->short_id'
        ),
		'title',
		'createdate',
        array(
            'name' => 'author_id',
            'value' => '$data->author->username'
        ),
        array(
            'name' => 'status_id',
            'value' => '$data->status->name'
        ),
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/news/availablenews.php
<?php
if ($usePagination){
    $template = "{items}\n{pager}";
} else {
    $template = '{items}';
}
?>

<div class="news_preview_list">
<?php
$this->widget('zii.widgets.CListView', array(
    'dataProvider'=>$dataProvider,
    'template' => $template,
    'itemView'=>'/news/_newsPreview',
    'afterAjaxUpdate'=>'init2GIS',
    //'separator' => '<hr class="news-spliter"/>',
    'htmlOptions' => array(
        'class' => 'newsColumn'
    ),
    'pager' => array(
        'class' => 'CLinkPager',
        'header' => '',
        'htmlOptions' => array(
            'class' => 'news-pager'
        )
    ),
)); ?>
</div>

protected/views/news/create.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->breadcrumbs=array(
	'Все новости'=>array('index'),
	'Новая',
);
?>

<h1>Новая новость</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/news/index.php
<?php
/* @var $this NewsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = false;

$this->fullsize = true;
$empty = true;
?>

    <hr class="news-spliter"/>
    <h1 class="by-center">Все новости</h1>
    <hr class="news-spliter"/>


<?php if ($dataProvider->itemCount) { ?>
    <?php $this->renderPartial('/news/availablenews', array(
        'dataProvider' => $dataProvider,
        'usePagination' => true
    )); ?>
    <?php $empty = false; ?>
<?php }?>

<?php if ($empty) {?>
    <h2>Ой-ой-ой, Новостей нет!</h2>
    <p>Все новости куда-то пропали! Возможно идут какие-то работы на сайте. Зайдите попозже ;)</p>
<?php }?>

protected/views/news/update.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->breadcrumbs=array(
	'Все новости'=>array('index'),
	'"'.$model->title.'"'=>array('view','id'=>$model->short_id),
    'Редактирование'
);
?>

<h1>Редкатирование новости: <i>"<?php echo $model->title; ?></i>"</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/news/view.php
<?php
/* @var $this NewsController */
/* @var $model News */

if($model->image) {
    $this->image = '/images/news/'.$model->image;
}

$this->breadcrumbs=array(
	'Новости'=>array('index'),
	$model->title,
);

Yii::app()->clientScript->registerScriptFile('/js/comments.js',CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScriptFile('/js/social_website.js',CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScriptFile('/js/newsImageZoom.js',CClientScript::POS_HEAD);

?>
<div class="news-full-data">

    <div class="single_news">

        <div class="news_title_box">
            <div class="news_title">
                <h2><?=CHtml::encode($model->title)?></h2>
            </div>
            <?php if (Yii::app()->user->checkAccess('m_content')) {?>
                <div class="news_status">
                    <?php echo CHtml::link(CHtml::encode($model->status->name), array('/news/update', 'id'=>$model->short_id)); ?>
                </div>
            <?php } ?>
        </div>

        <div class="news_preview">
            <?=$model->text?>
        </div>

        <div class="news_footer_box">
            <div class="news_share">
                <a onclick="sendwallpost('<?=Yii::app()->createUrl('news/view', array('id'=>$model->short_id))?>');" class="btn btn-info">Рассказать в VK</a>
            </div>

            <?php if (Yii::app()->user->checkAccess('m_content')) {?>
                <div class="news_date">
                    <?php echo CHtml::encode($model->createdate); ?>
                </div>

                <div class="news_author">
                    <?php echo CHtml::encode($model->author->user_profile->FullName); ?>
                </div>
            <?php } ?>

        </div>

        <hr class="news-spliter comment-padding"/>
        <script>
            var news_id = "<?=$model->short_id?>";
        </script>
        <div id="outer-comment-box"></div>
    </div>
</div>

<?php $this->renderPartial('/news/_showImage'); ?>